// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdVRvS3mxGT7GNkCKzWb4OY-wqP2hjzx0',
    appId: '1:607725154174:web:60ee3c6f32a8256caecd2f',
    messagingSenderId: '607725154174',
    projectId: 'fashion-store-f3185',
    authDomain: 'fashion-store-f3185.firebaseapp.com',
    storageBucket: 'fashion-store-f3185.firebasestorage.app',
    measurementId: 'G-LW09JF0EX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgD97zm-4xoEneRnj5L-UIIw5MQxm8cSY',
    appId: '1:607725154174:android:a5d3e83cbb77d536aecd2f',
    messagingSenderId: '607725154174',
    projectId: 'fashion-store-f3185',
    storageBucket: 'fashion-store-f3185.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXMr49LqaYTHWLQ2nzfZF4hc-GLgCKroE',
    appId: '1:607725154174:ios:627a762758311d4baecd2f',
    messagingSenderId: '607725154174',
    projectId: 'fashion-store-f3185',
    storageBucket: 'fashion-store-f3185.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXMr49LqaYTHWLQ2nzfZF4hc-GLgCKroE',
    appId: '1:607725154174:ios:627a762758311d4baecd2f',
    messagingSenderId: '607725154174',
    projectId: 'fashion-store-f3185',
    storageBucket: 'fashion-store-f3185.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdVRvS3mxGT7GNkCKzWb4OY-wqP2hjzx0',
    appId: '1:607725154174:web:14ba2816997a1754aecd2f',
    messagingSenderId: '607725154174',
    projectId: 'fashion-store-f3185',
    authDomain: 'fashion-store-f3185.firebaseapp.com',
    storageBucket: 'fashion-store-f3185.firebasestorage.app',
    measurementId: 'G-5W22X00F27',
  );
}
